export interface User {
    name: string,
    sub: string,
    num: string,
    email: string,
    add: string,
    uniname: string,
    deg: string,
    major: string,
    yearpass: string,
    company: string,
    pos: string,
    achieve: string,
    year: string,
    skill1: string,
    skill2: string,
    skill3: string,
    skill4: string,
    skill5: string,
}